### PR TITLE
Move another sidebar texts to locales

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
@yonathan06 Is this PR ok or not? I was looking to "Control panel" string originally and it's translatable :-)

**Comment by yonathan06** [comment]
Hi @michal-josef-spacek, do you it is necessary without translation? it is the same in all languages in you PR

**Comment by michal-josef-spacek** [comment]
@yonathan06 That's for backward compatibility with actual situation. I don't know how to translate to other language. This three languages are absolutely outside of me :-).
Control panel, translated by google translator, Swedish is probably right, pt too, Hebrew i don't know:
he: לוח בקרה
pt: Painel de controle
sv: Kontrollpanel

I am translating to Czech and this term i know :-)

**Comment by yonathan06** [comment]
The Hebrew one is ok :)
I'm approving the PR, we could translate the rest later

**Comment by michal-josef-spacek** [comment]
@yonathan06 Thank you :-)

**Pull request merged**
